### ISSUE TITLE
Validation errors when admin URL is different from site URL

### ISSUE THREAD

**Issue by ryanwelcher** [10up/maps-block-apple#34] opened 2020-06-19 18:12 UTC
**Describe the bug**
In testing a zip, I discovered if WordPress installed in a subdirectory, the request made to authenticate fails.

**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Environment information**
 - Device: 
 - OS: 
 - Browser and version: 
 - WordPress version: 
 
 - Plugins and version: 
 - Theme and version: 
 
 - <details><summary>Site Health Info:</summary>
   
   </details>

**Additional context**

**Comment by dinhtungdu** [comment] 2020-08-02 07:22
I can't reproduce this issue. Look like it was fixed by 92f03d08e5ec36f179b4c7fa94ac8112dde3878a

**Closed by dinhtungdu** 2020-08-02 07:22 UTC
Labels: bug, help wanted
